- platform: rgbww
  name: ${devicename}_rgb
  id: ${devicename}_rgb
  red: output_red
  green: output_green
  blue: output_blue
  warm_white: output_white
  cold_white: output_white
#  cold_white_color_temperature: 6200 K
#  warm_white_color_temperature: 2800 K
  default_transition_length: 3s
  restore_mode: RESTORE_DEFAULT_OFF
#  effects: !include effects.yaml
  color_interlock: true
