fast_connect: true
domain: !secret domain # pragma: allowlist secret
networks:
  - ssid: !secret phx_not_ssid # pragma: allowlist secret
    password: !secret phx_not_psk # pragma: allowlist secret
    hidden: true
ap:
  ssid: !secret fallback_ssid # pragma: allowlist secret
  password: !secret fallback_psk # pragma: allowlist secret
