#██╗      ██████╗  ██████╗  ██████╗ ██╗███╗   ██╗ ██████╗
#██║     ██╔═══██╗██╔════╝ ██╔════╝ ██║████╗  ██║██╔════╝
#██║     ██║   ██║██║  ███╗██║  ███╗██║██╔██╗ ██║██║  ███╗
#██║     ██║   ██║██║   ██║██║   ██║██║██║╚██╗██║██║   ██║
#███████╗╚██████╔╝╚██████╔╝╚██████╔╝██║██║ ╚████║╚██████╔╝
#╚══════╝ ╚═════╝  ╚═════╝  ╚═════╝ ╚═╝╚═╝  ╚═══╝ ╚═════╝
#
logger:
  default: warn
  logs:
    custom_components.google_fit: debug
    custom_components.sensor.places: debug
    homeassistant.components.google_assistant.http: debug
    homeassistant.components.google_cloud: debug
    homeassistant.components.google: debug
    homeassistant.components.http.ban: warning
    custom_components.sensor.authenticated: debug
    homeassistant.components.icloud: debug
    aiounifi: warn
    homeassistant.components.unifi: warn
    homeassistant.components.device_tracker.unifi: warn
    homeassistant.components.switch.unifi: warn
    homeassistant.components.automation: warn
    aioesphomeapi.connection: warn
recorder:
  purge_keep_days: 10
  db_url: !secret dburl # pragma: allowlist secret
  exclude:
    domains:
      - device_tracker
      - media_player
      - uptime
      - time_date
      - worldclock
      - updater
      - camera
      - media_player
      - weather
      - sun
      - image_processing
      - light
      - automation
      - group
      - script
      - switch
      - zone
      - time
    entity_globs:
      - sensor.clock*
      - sensor.date*
      - sensor.load_*
      - sensor.time*
      - sensor.uptime*
      - sensor.*_uptime
      - sensor.network_*
      - sensor.unifi_*
      - sensor.core*
logbook:
  exclude:
    entity_globs:
      - sensor.clock*
      - sensor.date*
      - sensor.time*
      - sensor.uptime*
      - sensor.*_uptime
      - sensor.network_*
    domains:
      - updater
      - camera
      - media_player
      - weather
      - sun
      - image_processing
      - device_tracker
history:
system_log:
  fire_event: true
  max_entries: 500
