#██╗      ██████╗  ██████╗  ██████╗ ██╗███╗   ██╗ ██████╗
#██║     ██╔═══██╗██╔════╝ ██╔════╝ ██║████╗  ██║██╔════╝
#██║     ██║   ██║██║  ███╗██║  ███╗██║██╔██╗ ██║██║  ███╗
#██║     ██║   ██║██║   ██║██║   ██║██║██║╚██╗██║██║   ██║
#███████╗╚██████╔╝╚██████╔╝╚██████╔╝██║██║ ╚████║╚██████╔╝
#╚══════╝ ╚═════╝  ╚═════╝  ╚═════╝ ╚═╝╚═╝  ╚═══╝ ╚═════╝
#
logger:
  default: info
  logs:
    custom_components.sensor.places: debug
    custom_components.deepstack_objects: debug
    homeassistant.components.sensor.deutsche_bahn: debug
    homeassistant.components.google_assistant.http: debug
    homeassistant.components.google_cloud: debug
    homeassistant.components.google: debug
    homeassistant.components.http.ban: warning
    custom_components.sensor.authenticated: debug
    homeassistant.components.icloud: debug
    aiounifi: warn
    homeassistant.components.unifi: warn
    homeassistant.components.device_tracker.unifi: warn
    homeassistant.components.switch.unifi: warn
    homeassistant.components.automation: warn
    aioesphomeapi.connection: warn
recorder:
  purge_keep_days: 30
  db_url: !secret dburl # pragma: allowlist secret
  exclude:
    domains:
      - updater
      - camera
      - weather
      - sun
      - image_processing
      - group
      - script
      - zone
      - time
    entity_globs:
      - sensor.*time*
      - sensor.time*
      - sensor.*date*
      - sensor.date*
      - sesnor.load
      - sensor.*load*
      - sensor.*free*
      - sensor.*mem*
      - sensor.processor_use
logbook:
  exclude:
    entity_globs:
      - sensor.*time*
      - sensor.time*
      - sensor.*date*
      - sensor.date*
      - sesnor.load
      - sensor.*load*
      - sensor.*free*
      - sensor.*mem*
      - sensor.processor_use
    domains:
      - updater
      - camera
      - weather
      - sun
      - image_processing
      - group
      - script
      - zone
      - time
history:
  exclude:
    domains:
      - updater
      - camera
      - weather
      - sun
      - image_processing
      - group
      - script
      - zone
      - time
