# ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ ██╗   ██╗██████╗  █████╗ ████████╗██╗ ██████╗ ███╗   ██╗
#██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ ██║   ██║██╔══██╗██╔══██╗╚══██╔══╝██║██╔═══██╗████╗  ██║
#██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗██║   ██║██████╔╝███████║   ██║   ██║██║   ██║██╔██╗ ██║
#██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║██║   ██║██╔══██╗██╔══██║   ██║   ██║██║   ██║██║╚██╗██║
#╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝╚██████╔╝██║  ██║██║  ██║   ██║   ██║╚██████╔╝██║ ╚████║
# ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
panel_iframe: !include panels.yaml
sensor: !include_dir_merge_list sensors/
# homeassistant starts here most stuff is in integrations directory
homeassistant:
  packages: !include_dir_named integrations/
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  auth_providers:
    - type: homeassistant
  #    - type: trusted_networks
  #      allow_bypass_login: true
  #      trusted_networks:
  #        - !secret trusted_network_2
  auth_mfa_modules:
    - type: totp
      name: Authy
  #    - type: notify
  #      message: "Hey, to get into my clubhouse, you need to say {}"
  external_url: !secret hassio_external_url
  internal_url: !secret hassio_internal_url
  name: Home
  time_zone: Europe/Berlin
  unit_system: metric
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: !secret home_ela
  allowlist_external_dirs: #seddelete
    - /config/tmp/ #seddelete
    - /config/media/ #seddelete
  allowlist_external_urls: #seddelete
    - https://localhost:8123 #seddelete
    - https://hassio.local.phixion.org/api/media_player_proxy #seddelete
  #https://www.home-assistant.io/integrations/media_source/
  media_dirs: #seddelete
    local: /config/media #seddelete
#    recording: /media/rec #seddelete
