- platform: waste_collection_schedule
  source_index: 0
  name: Müllabfuhr
  details_format: upcoming
  count: 10
  leadtime: 10
  value_template: '{{value.types|join(", ")}} am {{value.date.strftime("%a, %d.%m.%Y")}}'