- alias: Notification Low Disk Space
  id: "23"
  description: Notify me of low disk space
  trigger:
    - platform: numeric_state
      entity_id: sensor.disk_use_percent
      above: 80
      for: "00:10:00"
  action:
    - service: notify.gotify
      data_template:
        title: Main disk is almost full!
        message: "Diskusage: {{states(trigger.entity_id)}}"
        #priority: 7
    - service: notify.cloxion
      data:
        message: "hassio diskusage: {{states(trigger.entity_id)}}"
        data:
          sound: "notification"
          icon: "a35325"
          cycles: 3
          priority: "critical"
