- alias: Notification UniFi Alert
  id: "8"
  trigger:
    - platform: state
      entity_id: sensor.unifi_gateway_alerts
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{trigger.from_state.state > trigger.to_state.state}}"
      - condition: template
        value_template: "{{(trigger.to_state.state | default(0) | float) >= 1 }}"
  action:
    - service: notify.telegram
      data_template:
        title: UniFi Alert
        message: >
          {{states('sensor.unifi_gateway_alerts')}}
          {{states.sensor.unifi_gateway_alerts.attributes}}
#    - service: rest_command.assistant_broadcast
#      data_template:
#        command: Hey Martin, Es ist ein Fehler auf deinem Router, schau besser nach.

#- alias: Notification UniFi Guest Logon
#  id: "9"
#  trigger:
#    - platform: state
#      entity_id: sensor.unifi_wlan_guest
#  condition:
#    condition: and
#    conditions:
#      - condition: template
#        value_template: "{{trigger.from_state.state > trigger.to_state.state}}"
#      - condition: template
#        value_template: "{{(trigger.to_state.state | default(0) | float) >= 1 }}"
#  action:
#    - service: notify.telegram
#      data_template:
#        title: Ein Gast hat sich in dein Netzwerk eingeloggt.
#        message: >
#          Zur Zeit ist/sind {{states('sensor.unifi_wlan_guest')}} Gaste/Gäste in deinem Netzwerk.
#    - service: rest_command.assistant_broadcast
#      data_template:
#        command: Hey Martin, Ein Gast hat sich in dein Netzwerk eingeloggt.
