- alias: Notification Update
  id: "7"
  trigger:
    platform: state
    entity_id: binary_sensor.backups_stale
    to: "on"
  action:
    - data:
        message: Backup is stale!
        title: Backup is stale!
        #priority: 7
      service: notify.gotify
