- alias: Notification Channel 5 Video
  id: "15a"
  trigger:
    - platform: state
      entity_id: sensor.yt_channel5
      attribute: video_url
  condition:
    - condition: template
      value_template: "{{ as_timestamp(now()) - as_timestamp(states.automation.notification_channel_5_video.attributes.last_triggered) | int > 900 }}"
    - condition: template
      value_template: "{{ states.automation.notification_channel_5_video.attributes.last_triggered != none }}"
  action:
    - service: notify.cloxion
      data:
        message: "Neues Channel 5 Video: {{states.sensor.yt_channel5.state}}"
        data:
          sound: "notification"
          icon: "a10835"
          cycles: 0
          lifetime: 3600
          priority: "critical"
    - service: notify.android_tv
      data_template:
        title: "Neues Channel 5 Video: {{states.sensor.yt_channel5.state}}"
        message: " "
- alias: "AndroidTV Play Latest Channel 5 Video"
  id: "32"
  trigger:
    platform: state
    entity_id: input_boolean.play_latest_channel_5
    to: "on"
  action:
    - service: media_extractor.play_media
      entity_id:
        - media_player.fernseher
      data_template:
        media_content_id: "{{state_attr('sensor.yt_channel5', 'video_url' | string)}}"
        media_content_type: video/youtube
    - service: homeassistant.turn_off
      entity_id: input_boolean.play_latest_channel_5
