- alias: Notification Nexpo Video
  id: "11"
  trigger:
    - platform: state
      entity_id: sensor.yt_nexpo
      attribute: video_url
  condition:
    - condition: template
      value_template: "{{ as_timestamp(now()) - as_timestamp(states.automation.notification_nexpo_video.attributes.last_triggered) | int > 900 }}"
    - condition: template
      value_template: "{{ states.automation.notification_nexpo_video.attributes.last_triggered != none }}"
  action:
    - service: rest_command.assistant_broadcast
      data_template:
        command: Hey Martin, Nexpo hat ein neues Video auf YouTube hochgeladen.
    - service: notify.cloxion
      data:
        message: "Neues Nexpo Video {{states.sensor.yt_nexpo.state}}"
        data:
          sound: "notification"
          icon: "a10835"
          cycles: 10
          priority: "critical"
    - service: notify.android_tv
      data_template:
        title: "Neues Nexpo Video: {{states.sensor.yt_nexpo.state}}"
        message: " "
- alias: AndroidTV Play Latest Nexpo Video
  id: "28"
  trigger:
    platform: state
    entity_id: input_boolean.play_latest_nexpo
    to: "on"
  action:
    - service: media_extractor.play_media
      entity_id:
        - media_player.fernseher
      data_template:
        media_content_id: "{{state_attr('sensor.yt_nexpo', 'video_url' | string)}}"
        media_content_type: video/youtube
    - service: homeassistant.turn_off
      entity_id: input_boolean.play_latest_nexpo
