- alias: Notification Cheese Forever Video
  id: "114"
  trigger:
    - platform: state
      entity_id: sensor.yt_cheeseforever
      attribute: video_url
  condition:
    - condition: template
      value_template: "{{ as_timestamp(now()) - as_timestamp(states.automation.notification_cheese_forever_video.attributes.last_triggered) | int > 900 }}"
    - condition: template
      value_template: "{{ states.automation.notification_cheese_forever_video.attributes.last_triggered != none }}"
  action:
    - service: notify.cloxion
      data_template:
        message: "Neues Cheese Forever Video: {{states.sensor.yt_cheeseforever.state}}"
        data:
          sound: "notification"
          icon: "a10835"
          cycles: 0
          lifetime: 3600
          priority: "critical"
    - service: notify.android_tv
      data_template:
        title: "Neues Cheese Forever Video: {{states.sensor.yt_cheeseforever.state}}"
        message: " "
- alias: "AndroidTV Play Latest Cheese Forever"
  id: "133"
  trigger:
    platform: state
    entity_id: input_boolean.play_latest_cheeseforever
    to: "on"
  action:
    - service: media_extractor.play_media
      entity_id:
        - media_player.fernseher
      data_template:
        media_content_id: "{{state_attr('sensor.yt_cheeseforever', 'video_url' | string)}}"
        media_content_type: video/youtube
    - service: homeassistant.turn_off
      entity_id: input_boolean.play_latest_cheeseforever
