- alias: AndroidTV Play Latest JB3 Video
  id: "30"
  trigger:
    platform: state
    entity_id: input_boolean.play_latest_jb3
    to: "on"
  action:
    - service: media_extractor.play_media
      entity_id:
        - media_player.fernseher
      data_template:
        media_content_id: "{{state_attr('sensor.yt_jb3', 'video_url' | string)}}"
        media_content_type: video/youtube
    - service: homeassistant.turn_off
      entity_id: input_boolean.play_latest_jb3
- alias: Notification JB3 Video
  id: "10"
  trigger:
    - platform: state
      entity_id: sensor.yt_jb3
      attribute: video_url
  condition:
    - condition: template
      value_template: "{{ as_timestamp(now()) - as_timestamp(states.automation.notification_jb3_video.attributes.last_triggered) | int > 900 }}"
    - condition: template
      value_template: "{{ states.automation.notification_jb3_video.attributes.last_triggered != none }}"
  action:
    - service: notify.cloxion
      data:
        message: "Neues JB3 Video: {{states.sensor.yt_jb3.state}}"
        data:
          sound: "notification"
          icon: "a10835"
          cycles: 0
          lifetime: 3600
          priority: "critical"
