- alias: Notification froggy Video
  id: "11a"
  trigger:
    - platform: state
      entity_id: sensor.yt_froggy
      attribute: video_url
  condition:
    - condition: template
      value_template: "{{ as_timestamp(now()) - as_timestamp(states.automation.notification_froggy_video.attributes.last_triggered) | int > 900 }}"
    - condition: template
      value_template: "{{ states.automation.notification_froggy_video.attributes.last_triggered != none }}"
  action:
    - service: rest_command.assistant_broadcast
      data_template:
        command: "Hey Martin, froggy hat ein neues Video auf YouTube hochgeladen. {{states.sensor.yt_froggy.state}}"
    - service: notify.cloxion
      data:
        message: "Neues froggy Video: {{states.sensor.yt_froggy.state}}"
        data:
          sound: "notification"
          icon: "a10835"
          cycles: 0
          lifetime: 3600
          priority: "critical"
- alias: AndroidTV Play Latest froggy Video
  id: "28a"
  trigger:
    platform: state
    entity_id: input_boolean.play_latest_froggy
    to: "on"
  action:
    - service: media_extractor.play_media
      entity_id:
        - media_player.fernseher
      data_template:
        media_content_id: "{{state_attr('sensor.froggy', 'video_url' | string)}}"
        media_content_type: video/youtube
    - service: homeassistant.turn_off
      entity_id: input_boolean.play_latest_froggy
