- alias: Notification Incognito Mode Video
  id: "15b"
  trigger:
    - platform: state
      entity_id: sensor.yt_incognitomode
      attribute: video_url
  condition:
    - condition: template
      value_template: "{{ as_timestamp(now()) - as_timestamp(states.automation.notification_incognitomode_video.attributes.last_triggered) | int > 900 }}"
    - condition: template
      value_template: "{{ states.automation.notification_incognitomode_video.attributes.last_triggered != none }}"
  action:
    - service: notify.cloxion
      data:
        message: "Neues Incognito Mode Video: {{states.sensor.yt_incognitomode.state}}"
        data:
          sound: "notification"
          icon: "a10835"
          cycles: 0
          lifetime: 3600
          priority: "critical"
    - service: notify.android_tv
      data_template:
        title: "Neues Incognito Mode Video: {{states.sensor.yt_incognitomode.state}}"
        message: " "
- alias: "AndroidTV Play Latest Incognito Mode Video"
  id: "32"
  trigger:
    platform: state
    entity_id: input_boolean.play_latest_incognitomode
    to: "on"
  action:
    - service: media_extractor.play_media
      entity_id:
        - media_player.fernseher
      data_template:
        media_content_id: "{{state_attr('sensor.yt_incognitomode', 'video_url' | string)}}"
        media_content_type: video/youtube
    - service: homeassistant.turn_off
      entity_id: input_boolean.play_latest_incognitomode
