substitutions:
  devicename: bulbflur
  room: Flur
  friendly_name: Lampe
  update_interval_short: 2min
  update_interval_long: 10min
  frequency_rgb: 1000 Hz
  frequency_cw: 1000 Hz
  frequency_ww: 1000 Hz
esphome:
  esp8266_restore_from_flash: true
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  on_boot:
    priority: 100
    then:
      - light.turn_on:
          state: True
          id: ${devicename}_cwww
          transition_length: 3s
          white: 100%
          brightness: 100%
      - light.turn_off:
          id: ${devicename}_rgb
          transition_length: 0s
globals: !include shared/globals.yaml
##web_server: !include shared/webserver.yaml
time: !include shared/time.yaml
sensor: !include shared/sensors.yaml
binary_sensor: !include shared/binarysensors.yaml
output: !include shared/rgbcwwwoutput.yaml
light: !include shared/rgbcwww.yaml
text_sensor: !include shared/textsensors.yaml
wifi: !include shared/wifi.yaml
api: !include shared/api.yaml
ota: !include shared/ota.yaml
captive_portal:
logger:
switch:
  - platform: restart
    name: ${friendly_name} (${room}) Restart
