substitutions:
  devicename: nodemcu6
  friendly_name: Nodemcu 6
  room: Küche
  update_interval_short: 2min
  update_interval_long: 10min
esphome:
  name: ${devicename}
esp32:
  board: nodemcu-32s

wifi: !include shared/wifi.yaml
api: !include shared/api.yaml
ota: !include shared/ota.yaml
text_sensor: !include shared/textsensors.yaml
#web_server: !include shared/webserver.yaml
captive_portal:
logger:
sensor:
  - platform: wifi_signal
    name: ${friendly_name} (${room}) WiFi Signal
    update_interval: ${update_interval_long}
    unit_of_measurement: dB
    icon: mdi:wifi
  - platform: uptime
    force_update: true
    id: ${devicename}_uptime
    internal: true
    update_interval: ${update_interval_long}
uart:
  rx_pin: GPIO3
  baud_rate: 9600

# Declare GPS module
gps:
  latitude:
    name: "Latitude"
  longitude:
    name: "Longitude"
  altitude:
    name: "Altitude"

# GPS as time source
time:
  - platform: gps
switch:
  - platform: restart
    name: ${friendly_name} (${room}) Restart
