substitutions:
  devicename: nodemcu5
  friendly_name: Nodemcu 5
  room: Bad
  update_interval_short: 2min
  update_interval_long: 10min
esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2
time: !include shared/time.yaml
wifi: !include shared/wifi.yaml
api: !include shared/api.yaml
ota: !include shared/ota.yaml
#web_server: !include shared/webserver.yaml
captive_portal:
logger:
sensor: !include shared/sensors.yaml
text_sensor: !include shared/textsensors.yaml
binary_sensor:
  - platform: gpio
    pin: D1
    device_class: motion
    name: ${friendly_name} (${room}) Doppler Sensor
    id: ${devicename}_doppler
    filters:
      - delayed_off: 10ms
      - delayed_on: 200ms
  - platform: template
    id: ${devicename}_templ_doppler
    internal: true
    lambda: 'return id(${devicename}_doppler).state;'
    filters:
      - delayed_off: 3min
    on_press:
      - homeassistant.service:
          service: switch.turn_on
          data:
            entity_id: switch.schalter_1_bad_relay
    on_release:
      - homeassistant.service:
          service: switch.turn_off
          data:
            entity_id: switch.schalter_1_bad_relay
  - platform: status
    device_class: connectivity
    name: ${friendly_name} (${room}) Status
switch:
  - platform: restart
    name: ${friendly_name} (${room}) Restart
