---
name: Home Assistant CI
# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *
jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get -qq update && sed 's/#.*//' $(pwd)/.doc/CI/ubuntu_deps.lst | xargs sudo apt-get install -y -o Dpkg::Options::=--force-confnew
      - name: Copy stub files into configuration folder
        run: cp -R ./.doc/CI/* .
      - name: remove unwanted configuration entries from configuration.yaml
        run: sed -i '/#seddelete/d' configuration.yaml
      - name: remove unwanted configuration entries from integrations/http.yaml
        run: sed -i '/#seddelete/d' integrations/http.yaml
      - name: remove unwanted configuration entries from integrations/folder_watcher.yaml
        run: sed -i '/#seddelete/d' integrations/folder_watcher.yaml
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config . --script check_config --info all
  beta:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get -qq update && sed 's/#.*//' $(pwd)/.doc/CI/ubuntu_deps.lst | xargs sudo apt-get install -y -o Dpkg::Options::=--force-confnew
      - name: Copy stub files into configuration folder
        run: cp -R ./.doc/CI/* .
      - name: remove unwanted configuration entries from configuration.yaml
        run: sed -i '/#seddelete/d' configuration.yaml
      - name: remove unwanted configuration entries from integrations/http.yaml
        run: sed -i '/#seddelete/d' integrations/http.yaml
      - name: remove unwanted configuration entries from integrations/folder_watcher.yaml
        run: sed -i '/#seddelete/d' integrations/folder_watcher.yaml
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: python -m homeassistant --config . --script check_config --info all
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get -qq update && sed 's/#.*//' $(pwd)/.doc/CI/ubuntu_deps.lst | xargs sudo apt-get install -y -o Dpkg::Options::=--force-confnew
      - name: Copy stub files into configuration folder
        run: cp -R ./.doc/CI/* .
      - name: remove unwanted configuration entries from configuration.yaml
        run: sed -i '/#seddelete/d' configuration.yaml
      - name: remove unwanted configuration entries from integrations/http.yaml
        run: sed -i '/#seddelete/d' integrations/http.yaml
      - name: remove unwanted configuration entries from integrations/folder_watcher.yaml
        run: sed -i '/#seddelete/d' integrations/folder_watcher.yaml
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:dev"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:dev"
        with:
          args: python -m homeassistant --config . --script check_config --info all
